ROSTemplateFormatVersion: '2015-09-01'
# 定义参数
Parameters:
  Parameters:
    Type: Json
    AssociationProperty: List[Parameters]
    AssociationPropertyMetadata:
      Parameters:
        Name:
          Type: String
        Label:
          Type: String
        Type:
          Type: String
          AllowedValues:
            - Integer
            - String
            - Boolean
            - Json
        AllowedValues:
          Type: Json
          AssociationProperty: List
          AssociationPropertyMetadata:
            Multiple: true
          Default: Null
          Required: false
        NoEcho:
          Type: Boolean
          Default: false
          AllowedValues:
            - true
            - false
        AssociationProperty:
          Type: String
          Default: Null
          Required: false
          AssociationProperty: AssociationProperty
    Default:
    - Name: AdminPassword
      NoEcho: true
      Type: String
      Label: 管理员密码
      AssociationProperty: ALIYUN::ECS::Instance::Password
  DockerComposeYaml:
    Type: String
    Label:
      en: artifact version
      zh-cn: 部署物版本
    AssociationProperty: Code
    Default: |-
      services:
        hello_world:
          image: {{computenest::acrimage::nginx}}
          ports:
            - 80:80
  PreStartCommand:
    Type: String
    AssociationProperty: Code
    Default: |
      #!/bin/bash
      echo ${AdminPassword}
  PostStartCommand:
    Type: String
    AssociationProperty: Code
    Default: |
      #!/bin/bash
      echo ${AdminPassword}
  CommandTimeout:
    Type: Number
    Default: 300
  DockerImageArtifactId:
    Type: String
    Label:
      en: artifact id
      zh-cn: 部署物Id
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactId
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactType: AcrImage
  DockerImageArtifactVersion:
    Type: String
    Label:
      en: artifact version
      zh-cn: 部署物版本
    AssociationProperty: ALIYUN::ComputeNest::Artifact::ArtifactIdVersion
    AssociationPropertyMetadata:
      IsSupplier: true
      ArtifactId: ${DockerImageArtifactId}
  Ports:
    Type: Json
    Label:
      en: security group ports
      zh-cn: 安全组开放端口
    AssociationProperty: List
    AssociationPropertyMetadata:
      Multiple: true
    Default:
      - 80
    Required: true
    MinLength: 1
  InstanceTypes:
    Type: Json
    Label:
      en: Ecs InstanceTypes
      zh-cn: Ecs实例规格列表
    AssociationProperty: ALIYUN::ECS::Instance::InstanceType
    AssociationPropertyMetadata:
      Multiple: true
    Default:
      - ecs.c6.large
      - ecs.c6.xlarge
      - ecs.c6.2xlarge
  Outputs:
    Type: Json
    AssociationProperty: List[Parameters]
    AssociationPropertyMetadata:
      Parameters:
        DisplayName:
          Type: String
        Expression:
          Type: String
    Default:
    - DisplayName: Endpoint
      Expression: http://${Address}:80
Metadata:
  ALIYUN::ROS::Interface:
    # 定义资源分组，创建服务实例时，同一分组的参数分布在一起
    ParameterGroups:
      - Parameters:
          - Label: Docker镜像部署物
            Items:
              - DockerImageArtifactId
              - DockerImageArtifactVersion
          - Parameters
          - DockerComposeYaml
          - PreStartCommand
          - PostStartCommand
          - CommandTimeout
        Label:
          en: Deployment Configuration
          zh-cn: 软件配置
      - Parameters:
          - InstanceTypes
          - Ports
        Label:
          en: Security Configuration
          zh-cn: 实例配置
      - Parameters:
          - Outputs
        Label:
          en: Deployment Configuration
          zh-cn: 输出配置
