Parameters:
  - Name: AdminPassword
    NoEcho: true
    Type: String
    Label: 管理员密码
    AssociationProperty: ALIYUN::ECS::Instance::Password
DockerImageArtifacts:
  - Placeholder: 'computenest::acrimage::nginx'
    ArtifactId: artifact-xxx
    ArtifactVersion: "1"
DockerComposeYaml: |-
  services:
    nginx:
      image: {{computenest::acrimage::nginx}}
      ports:
        - 80:80
      volumes:
        - /home/admin/application/nginx/logs:/var/log/nginx/
PreStartCommand: |
  echo before start docker
  mkdir -p /home/admin/application/nginx/logs
PostStartCommand: |
  echo after start docker
CommandTimeout: 300
InstanceTypes:
  - ecs.c6.large
  - ecs.c6.xlarge
  - ecs.c6.2xlarge
Ports:
  - 80
Outputs:
  - DisplayName: Endpoint
    Expression: http://${Address}:80
