Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      AcrImageArtifactRelation:
        '{{computenest::acrimage::nginx}}':
          ArtifactId: artifact-xxx
          ArtifactVersion: 1
    TemplateConfigs:
      - Name: ECS单机版
        Url: 'ros_templates/template.yaml'
        AllowedRegions: []
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: docker compose deploy
    Image: 'resources/icons/service_logo.png'
    Name: DockerCompose部署单机版
  ShareType: Public
  ApprovalType: Manual